---
- name: delete everything created by vault_encrypted_passwords.yml
  hosts: all
  vars_files: users.yml
  tasks:
    - name: first remove users completely
      user:
        name: "{{ item.username }}"
        state: absent
        force: True
        remove: True
      loop: "{{ users }}"

    - name: then remove the groups created
      group:
        name: "{{ item.groups }}"
        state: absent
      loop: "{{ users }}"
