---
- name: Create a list of users using an Ansible-Vault Encrypted file to store passwords
  hosts: all
  vars_files: users.yml
  tasks:
    - name: add groups that users will belong to
      group:
        name: "{{ item.groups }}"
        state: present
      loop: "{{ users }}"
    - name: Just do a regular user create using variables defined in other files
      user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        shell: "{{ item.shell }}"
        groups: "{{ item.groups}}"
      loop: "{{ users }}"
