---
- name: REMOVE storage made using storage_msdos.yml
  hosts: all
  tasks:
    - name: manage mount three
      mount:
        fstype: ext4
        src: UUID="{{ ansible_facts['devices']['dm-4']['links']['uuids'][0] }}"
        state: absent
        path: /mnt/three

    - name: manage mount two
      mount:
        fstype: ext4
        src: 'LABEL=labelone'
        state: absent
        path: /mnt/two

    - name: manage mount one
      mount:
        fstype: ext4
        src: /dev/vgone/lvone
        state: absent
        path: /mnt/one
          
    - name: remove filesystem on lvthree
      filesystem:
        dev: /dev/vgthree/lvthree
        force: True
        fstype: ext4
        state: absent

    - name: remove filesystem on lvtwo
      filesystem:
        dev: /dev/vgtwo/lvtwo
        force: True
        fstype: ext4
        state: absent

    - name: remove fileystem on lvone
      filesystem:
        dev: /dev/vgone/lvone
        force: True
        fstype: ext4
        state: absent

    - name: remove lvs
      import_tasks: dellvs.yml

    - name: remove vgs 
      import_tasks: delvgs.yml

    - name: primary parition one
      parted:
        state: absent
        device: /dev/sdb
        number: 1
        label: msdos
        part_type: primary
        part_start: 100MiB
        part_end: 200MiB
        flags: [ lvm ]

    - name: primary parition two
      parted:
        state: absent
        device: /dev/sdb
        number: 2
        label: msdos
        part_type: primary
        part_start: 200MiB
        part_end: 300MiB
        flags: [ lvm ]

    - name: primary parition three
      parted:
        state: absent
        device: /dev/sdb
        number: 3
        label: msdos
        part_type: primary
        part_start: 300MiB
        part_end: 400MiB
        flags: [ lvm ]

    - name: extended partition 
      parted:
        state: absent
        device: /dev/sdb
        number: 4
        label: msdos
        part_type: extended
        part_start: 500MiB
        part_end: 4094MiB

    - name: logical partition five
      parted: 
        state: absent
        device: /dev/sdb
        number: 5
        label: msdos
        part_type: logical
        part_start: 510MiB
        part_end: 600MiB

    - name: logical partition six
      parted: 
        state: absent
        device: /dev/sdb
        number: 6
        label: msdos
        part_type: logical
        part_start: 610MiB
        part_end: 700MiB

    - name: logical partition seven
      parted: 
        state: absent
        device: /dev/sdb
        number: 7
        label: msdos
        part_type: logical
        part_start: 710MiB
        part_end: 800MiB

    - name: logical partition eight
      parted: 
        state: absent
        device: /dev/sdb
        number: 8
        label: msdos
        part_type: logical
        part_start: 810MiB
        part_end: 900MiB

    - name: logical partition nine
      parted: 
        state: absent
        device: /dev/sdb
        number: 9
        label: msdos
        part_type: logical
        part_start: 910MiB
        part_end: 1GiB

    - name: logical partition ten
      parted: 
        state: absent
        device: /dev/sdb
        number: 10
        label: msdos
        part_type: logical
        part_start: 1034MiB
        part_end: 2000MiB

    - name: logical partition eleven
      parted: 
        state: absent
        device: /dev/sdb
        number: 11
        label: msdos
        part_type: logical
        part_start: 2004MiB
        part_end: 3000MiB

    - name: logical partition twelve
      parted: 
        state: absent
        device: /dev/sdb
        number: 12
        label: msdos
        part_type: logical
        part_start: 3004MiB
        part_end: 4048MiB

- name: importing confirm.yml
  import_playbook: confirm.yml


